# Generated by Django 5.0 on 2025-11-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="presentation",
            name="pptx_file",
            field=models.FileField(
                blank=True, null=True, upload_to="pptx/", verbose_name="PowerPoint File"
            ),
        ),
    ]
