# Generated by Django 5.0 on 2025-12-03 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0003_emailverification"),
    ]

    operations = [
        migrations.AddField(
            model_name="presentation",
            name="presentation_type",
            field=models.CharField(
                choices=[
                    ("pdf", "PDF Only"),
                    ("pptx", "PowerPoint Only"),
                    ("both", "Both"),
                ],
                default="both",
                max_length=10,
                verbose_name="Presentation Type",
            ),
        ),
    ]
