# Generated by Django 5.0 on 2025-12-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0005_presentation_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="presentation",
            name="template_name",
            field=models.CharField(
                choices=[
                    ("classic", "Classic"),
                    ("modern", "Modern"),
                    ("creative", "Creative/Professional"),
                ],
                default="classic",
                max_length=20,
                verbose_name="Template Style",
            ),
        ),
    ]
