# Generated by Django 5.0 on 2025-12-06 22:42

import generator.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0006_presentation_template_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="presentation",
            name="unique_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="presentation",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=generator.models.presentation_directory_path,
                verbose_name="PDF File",
            ),
        ),
        migrations.AlterField(
            model_name="presentation",
            name="pptx_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=generator.models.presentation_directory_path,
                verbose_name="PowerPoint File",
            ),
        ),
    ]
