# Generated by Django 5.0 on 2025-12-06 22:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "generator",
            "0007_presentation_unique_id_alter_presentation_pdf_file_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="presentation",
            name="unique_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
