# Generated by Django 5.0 on 2025-12-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0008_alter_presentation_unique_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="presentation",
            name="article_data",
            field=models.JSONField(blank=True, null=True, verbose_name="Article Data"),
        ),
    ]
