# Generated by Django 5.0 on 2025-12-08 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0009_add_article_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="presentation",
            name="current_stage",
            field=models.CharField(
                default="pending",
                help_text="Current generation stage: pending, analyzing, generating, images, creating, finalizing, completed",
                max_length=50,
                verbose_name="Current Stage",
            ),
        ),
        migrations.AddField(
            model_name="presentation",
            name="estimated_time",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Estimated Time (seconds)"
            ),
        ),
        migrations.AddField(
            model_name="presentation",
            name="progress",
            field=models.IntegerField(default=0, verbose_name="Progress Percentage"),
        ),
        migrations.AddField(
            model_name="presentation",
            name="status_message",
            field=models.TextField(
                blank=True, default="", verbose_name="Status Message"
            ),
        ),
    ]
