# Generated by Django 5.0 on 2025-12-08 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0010_presentation_current_stage_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="presentation",
            name="current_stage",
        ),
        migrations.RemoveField(
            model_name="presentation",
            name="estimated_time",
        ),
        migrations.RemoveField(
            model_name="presentation",
            name="progress",
        ),
        migrations.RemoveField(
            model_name="presentation",
            name="status_message",
        ),
    ]
