import os
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN
from pptx.dml.color import RGBColor
from django.conf import settings

class PPTXService:
    """Service for generating PowerPoint presentations"""

    def __init__(self, template_path=None):
        """
        Initialize with an optional template path.
        If no template is provided, a blank presentation is created.
        """
        self.template_path = template_path
        if template_path and os.path.exists(template_path):
            self.prs = Presentation(template_path)
        else:
            self.prs = Presentation()
            # Set 16:9 aspect ratio for blank presentation
            self.prs.slide_width = Inches(13.333)
            self.prs.slide_height = Inches(7.5)

    def generate_presentation(self, article: dict, image_paths: list, output_path: str):
        """
        Generate a PowerPoint presentation from the article and images.
        
        Args:
            article: Dictionary containing title, introduction, sections, etc.
            image_paths: List of paths to downloaded images.
            output_path: Path to save the generated PPTX file.
        """
        # 1. Title Slide
        self._create_title_slide(article.get('title', 'Presentation'))

        # 2. Introduction Slide
        if article.get('introduction'):
            self._create_content_slide("Introduction", article['introduction'], image_paths, 0)

        # 3. Section Slides
        sections = article.get('sections', [])
        
        # Create map for quick lookup
        image_map = {os.path.basename(p): p for p in image_paths}
        
        for i, section in enumerate(sections):
            # Resolve image path from section.image URL
            img_path = None
            if section.get('image'):
                image_url = section['image']
                if image_url.startswith('/media/'):
                     # Remove '/media/' and join with MEDIA_ROOT
                     relative_path = image_url.replace('/media/', '', 1)
                     import urllib.parse
                     relative_path = urllib.parse.unquote(relative_path)
                     
                     possible_path = os.path.join(str(settings.MEDIA_ROOT), relative_path)
                     if os.path.exists(possible_path):
                         img_path = str(possible_path)
            
            # Fallback to round-robin if no explicit image (optional, but let's stick to explicit only for Zen)
            if not img_path and image_paths:
                 img_path = str(image_paths[i % len(image_paths)])

            self._create_content_slide(section.get('title', ''), section.get('content', ''), img_path)

        # 4. Conclusion Slide
        if article.get('conclusion'):
            self._create_content_slide("Conclusion", article['conclusion'], None)

        # Save the presentation
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        self.prs.save(output_path)
        return output_path

    def _create_title_slide(self, title_text):
        """Create the title slide"""
        # ... (keep existing)
        slide_layout = self.prs.slide_layouts[0]
        slide = self.prs.slides.add_slide(slide_layout)
        title = slide.shapes.title
        subtitle = slide.placeholders[1]
        title.text = title_text
        subtitle.text = "Generated by AI Presentation Generator"
        self._style_text(title.text_frame.paragraphs[0], font_size=54, bold=True, color=RGBColor(44, 62, 80))
        self._style_text(subtitle.text_frame.paragraphs[0], font_size=24, color=RGBColor(127, 140, 141))

    def _create_content_slide(self, title_text, content_text, image_path):
        """Create a content slide with text and optional image"""
        slide_layout = self.prs.slide_layouts[6] 
        slide = self.prs.slides.add_slide(slide_layout)

        # Add Title
        left = Inches(0.5)
        top = Inches(0.5)
        width = Inches(12.333)
        height = Inches(1.0)
        txBox = slide.shapes.add_textbox(left, top, width, height)
        tf = txBox.text_frame
        tf.text = title_text
        self._style_text(tf.paragraphs[0], font_size=40, bold=True, color=RGBColor(44, 62, 80))

        # Content Layout
        if image_path and os.path.exists(image_path):
            # Text on left, Image on right
            text_left = Inches(0.5)
            text_top = Inches(1.8)
            text_width = Inches(7.0)
            text_height = Inches(5.0)
            
            img_left = Inches(8.0)
            img_top = Inches(1.8)
            img_width = Inches(4.8)
            
            try:
                slide.shapes.add_picture(image_path, img_left, img_top, width=img_width)
            except Exception as e:
                print(f"Error adding image {image_path}: {e}")
                text_width = Inches(12.333) # Fallback

        else:
            # Full width text
            text_left = Inches(0.5)
            text_top = Inches(1.8)
            text_width = Inches(12.333)
            text_height = Inches(5.0)

        # Add Text Content
        txBox = slide.shapes.add_textbox(text_left, text_top, text_width, text_height)
        tf = txBox.text_frame
        tf.word_wrap = True
        
        paragraphs = content_text.split('\n\n')
        for p_text in paragraphs:
            p = tf.add_paragraph()
            p.text = p_text.strip()
            p.space_after = Pt(14)
            self._style_text(p, font_size=18, color=RGBColor(50, 50, 50))

    def _style_text(self, paragraph, font_name='Calibri', font_size=18, bold=False, color=None):
        """Apply styling to a paragraph"""
        paragraph.font.name = font_name
        paragraph.font.size = Pt(font_size)
        paragraph.font.bold = bold
        if color:
            paragraph.font.color.rgb = color
